
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/fastsns"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379